import pandas as pd
import numpy as np

#
# Merged desired format example
#

# WT reclaimed wastewater released by wastewater facilities -
# WT number of wastewater facilities -
# WT number of public wastewater facilities 7
# WT returns by public wastewater facilities 142.32
# WT reclaimed wastewater released by public wastewater facilities -


# HP total number of facilities -
    # HP number of offstream facilities -
    # HP number of instream facilities -
# HP total power generated -
    # HP power generated by offstream use -
    # HP power generated by instream use 0.00
# HP total offstream surface-water withdrawals -
    # HP surface s-s offstream withdrawals -
    # HP offstream surface-water withdrawals -
# HP instream use 0.00



# Ir Golf Courses reclaimed wastewater for golf courses -
# Ir Golf Courses total irrigation for golf courses -
    # Ir Golf Courses surface irrigation for golf courses -
    # Ir Golf Courses microirrigation for golf courses -
    # Ir Golf Courses sprinkler irrigation for golf courses -
# Ir Golf Courses conveyance loss for golf courses -
# Ir Golf Courses consumptive use for golf courses -
# Ir Golf Courses total s-s withdrawals for golf courses -
    # Ir Golf Courses s-s surface-water withdrawals for golf courses -
    # Ir Golf Courses s-s groundwater withdrawals for golf courses -
# Ir Crop reclaimed wastewater for crops -
# Ir Crop total irrigation for crops -
    # Ir Crop surface irrigation for crops -
    # Ir Crop microirrigation for crops -
    # Ir Crop sprinkler irrigation for crops -
# Ir Crop conveyance loss for crops -
# Ir Crop consumptive use for crops -
# Ir Crop total s-s withdrawals for crops -
    # Ir Crop s-s surface-water withdrawals for crops -
    # Ir Crop s-s groundwater withdrawals for crops -
# Ir Total reclaimed wastewater 0.33
# Ir Total total irrigation -
    # Ir Total surface irrigation 9.01
    # Ir Total microirrigation -
    # Ir Total sprinkler irrigation 3.29
# Ir Total conveyance loss 0.28
# Ir Total total consumptive use -
    # Ir Total consumptive use.1 -
    # Ir Total consumptive use 16.11
# Ir Total total s-s withdrawals.2 -
    # Ir Total total s-s withdrawals.1 -
    # Ir Total total s-s withdrawals 23.44
        # Ir Total total s-s withdrawals surface -
            # Ir Total s-s surface-water withdrawals.1 -
            # Ir Total s-s surface-water withdrawals 15.61
        # Ir Total total s-s withdrawals groundwater -
            # Ir Total s-s groundwater withdrawals.1 -
            # Ir Total s-s groundwater withdrawals 7.83


# A total consumptive use -
    # A consumptive use.1 -
    # A consumptive use -
# A total s-s withdrawals.2 -
    # A total s-s withdrawals.1 -
    # A total s-s withdrawals -
        # A total s-s withdrawals surface -
            # A s-s surface-water withdrawals.1 -
            # A s-s surface-water withdrawals -
        # A total s-s withdrawals groundwater -
            # A s-s groundwater withdrawals.1 -
            # A s-s groundwater withdrawals -


# L (Animal Specialties) total consumptive use -
    # L (Animal Specialties) consumptive use.1 -
    # L (Animal Specialties) consumptive use -
# L (Animal Specialties) total s-s withdrawals.2 -
    # L (Animal Specialties) total s-s withdrawals.1 -
    # L (Animal Specialties) total s-s withdrawals -
        # L (Animal Specialties) total s-s withdrawals surface -
            # L (Animal Specialties) s-s surface-water withdrawals.1 -
            # L (Animal Specialties) s-s surface-water withdrawals -
        # L (Animal Specialties) total s-s withdrawals groundwater -
            # L (Animal Specialties) s-s groundwater withdrawals.1 -
            # L (Animal Specialties) s-s groundwater withdrawals -
# L (Stock) total consumptive use -
    # L (Stock) consumptive use.1 -
    # L (Stock) consumptive use 0.67
# L (Stock) total s-s withdrawals.2 -
    # L (Stock) total s-s withdrawals.1 -
    # L (Stock) total s-s withdrawals 0.73
        # L (Stock) total s-s withdrawals surface -
            # L (Stock) s-s surface-water withdrawals.1 -
            # L (Stock) s-s surface-water withdrawals 0.60
        # L (Stock) total s-s withdrawals groundwater -
            # L (Stock) s-s groundwater withdrawals.1 -
            # L (Stock) s-s groundwater withdrawals 0.13
# L consumptive use -
    # L total s-s withdrawals -
        # L s-s surface-water withdrawals -
        # L s-s groundwater withdrawals -


# M reclaimed wastewater -
# M total consumptive use 0.30
    # M consumptive use.1 0.19
    # M consumptive use 0.11
# M total s-s withdrawals.2 1.13
    # M total s-s withdrawals.1 0.73
    # M total s-s withdrawals 0.4
        # M total s-s withdrawals surface 0.2
            # M s-s surface-water withdrawals.1 0.06
            # M s-s surface-water withdrawals 0.14
        # M total s-s withdrawals groundwater 0.93
            # M s-s groundwater withdrawals.1 0.67
            # M s-s groundwater withdrawals 0.26


# TP (CL-C) number of facilities -
# TP (CL-C) reclaimed wastewater -
# TP (CL-C) power generated -
# TP (CL-C) total consumptive use -
    # TP (CL-C) consumptive use.1 -
    # TP (CL-C) consumptive use -
# TP (CL-C) total s-s withdrawals plus deliveries -
    # TP (CL-C) deliveries from public supply -
    # TP (CL-C) total s-s withdrawals total -
        # TP (CL-C) total s-s withdrawals.1 -
        # TP (CL-C) total s-s withdrawals -
        # TP (CL-C) total s-s withdrawals surface -
            # TP (CL-C) s-s surface-water withdrawals.1 -
            # TP (CL-C) s-s surface-water withdrawals -
        # TP (CL-C) total s-s withdrawals groundwater -
            # TP (CL-C) s-s groundwater withdrawals.1 -
            # TP (CL-C) s-s groundwater withdrawals -


# TP (OT-C) number of facilities -
# TP (OT-C) reclaimed wastewater -
# TP (OT-C) power generated -
# TP (OT-C) total consumptive use -
    # TP (OT-C) consumptive use.1 -
    # TP (OT-C) consumptive use -
# TP (OT-C) total s-s withdrawals plus deliveries -
    # TP (OT-C) deliveries from public supply -
    # TP (OT-C) total s-s withdrawals total -
        # TP (OT-C) total s-s withdrawals.1 -
        # TP (OT-C) total s-s withdrawals -
            # TP (OT-C) total s-s withdrawals surface -
                # TP (OT-C) s-s surface-water withdrawals.1 -
                # TP (OT-C) s-s surface-water withdrawals -
            # TP (OT-C) total s-s withdrawals groundwater -
                # TP (OT-C) s-s groundwater withdrawals.1 -
                # TP (OT-C) s-s groundwater withdrawals -


# NTP number of facilities -
# NTP reclaimed wastewater -
# NTP power generation 0.00
# NTP total consumptive use 0.00
    # NTP consumptive use.1 0.00
    # NTP consumptive use 0.00
# NTP total s-s withdrawals plus deliveries -
    # NTP deliveries from public supply 0.00
    # NTP total s-s withdrawals.2 -
        # NTP total s-s withdrawals.1 -
        # NTP total s-s withdrawals 0.00
            # NTP total s-s withdrawals surface 0.00
                # NTP s-s surface-water withdrawals.1 0.00
                # NTP s-s surface-water withdrawals 0.00
            # NTP total s-s withdrawals groundwater -
                # NTP s-s groundwater withdrawals.1 -
                # NTP s-s groundwater withdrawals 0.00


# GTP number of facilities -
# GTP reclaimed wastewater -
# GTP power generation 0.00
# GTP total consumptive use 0.00
    # GTP consumptive use.1 0.00
    # GTP consumptive use 0.00
# GTP total s-s withdrawals plus deliveries -
    # GTP deliveries from public supply 0.00
    # GTP total s-s withdrawals.2 -
        # GTP total s-s withdrawals.1 -
        # GTP total s-s withdrawals -
            # GTP total s-s withdrawals surface -
                # GTP s-s surface-water withdrawals.1 -
                # GTP s-s surface-water withdrawals -
            # GTP total s-s withdrawals groundwater 0.00
                # GTP s-s groundwater withdrawals.1 0.00
                # GTP s-s groundwater withdrawals 0.00


# FTP number of facilities -
# FTP reclaimed wastewater -
# FTP power generation 7.72
# FTP total consumptive use 0.00
    # FTP consumptive use.1 0.00
    # FTP consumptive use 0.00
# FTP total s-s withdrawals plus deliveries -
    # FTP deliveries from public supply 0.00
    # FTP total s-s withdrawals.2 -
        # FTP total s-s withdrawals.1 -
        # FTP total s-s withdrawals 0.00
            # FTP total s-s withdrawals surface 0.00
                # FTP s-s surface-water withdrawals.1 0.00
                # FTP s-s surface-water withdrawals 0.00
            # FTP total s-s withdrawals groundwater -
                # FTP s-s groundwater withdrawals.1 -
                # FTP s-s groundwater withdrawals 0.00


# TTP number of facilities -
# TTP reclaimed wastewater -
# TTP power generated 7.72
# TTP total consumptive use 0.00
    # TTP consumptive use.1 0.00
    # TTP consumptive use 0.00
# TTP total s-s withdrawals plus deliveries -
    # TTP total s-s withdrawals total -
            # TTP total s-s withdrawals.1 -
            # TTP total s-s withdrawals -
            # TTP total s-s withdrawals surface -
                # TTP s-s surface-water withdrawals.1 -
                # TTP s-s surface-water withdrawals -
            # TTP total s-s withdrawals groundwater -
                # TTP s-s groundwater withdrawals.1 -
                # TTP s-s groundwater withdrawals 0.0


# I number of facilities -
# I reclaimed wastewater 0.00
# I total consumptive use 2.53
    # I consumptive use.1 0.14
    # I consumptive use 2.39
# I total s-s withdrawals plus deliveries 10.12
    # I deliveries from public supply 6.24
    # I total s-s withdrawals.2 3.88
        # I total s-s withdrawals.1 0.61
        # I total s-s withdrawals 3.27
            # I total s-s withdrawals surface 0.62
                # I s-s surface-water withdrawals.1 0.61
                # I s-s surface-water withdrawals 0.01
            # I total s-s withdrawals groundwater 3.26
                # I s-s groundwater withdrawals.1 0.0
                # I s-s groundwater withdrawals 3.26


# C reclaimed wastewater -
# C total consumptive use -
    # C consumptive use.1 -
    # C consumptive use 11.67
# C total s-s withdrawals plus deliveries -
    # C deliveries from public supply 44.87
    # C total s-s withdrawals.2 -
        # C total s-s withdrawals.1 -
        # C total s-s withdrawals 1.19
            # C total s-s withdrawals surface -
                # C s-s surface-water withdrawals.1 -
                # C s-s surface-water withdrawals 0.10
            # C total s-s withdrawals groundwater -
                # C s-s groundwater withdrawals.1 -
                # C s-s groundwater withdrawals 1.09


# D reclaimed wastewater -
# D s-s population 42.05
# D per capita use s-s 75
# D total consumptive use -
# D per capita use public-supplied 103
    # D consumptive use.1 -
    # D consumptive use 31.76
# D total s-s withdrawals plus deliveries 122.16
    # D total s-s withdrawals.2 -
    # D deliveries from public supply 119.010
        # D total s-s withdrawals.1 -
        # D total s-s withdrawals 3.15
            # D total s-s withdrawals surface -
                # D s-s surface-water withdrawals.1 -
                # D s-s surface-water withdrawals 0.25
            # D total s-s withdrawals groundwater -
                # D s-s groundwater withdrawals.1 -
                # D s-s groundwater withdrawals 2.9


# PS number of facilities -
# PS reclaimed wastewater -
# PS per capita use -
# PS public use and losses -
# PS total deliveries 170.12
    # PS deliveries to thermoelectric 0.00
    # PS deliveries to industrial 6.24
    # PS deliveries to commercial 44.87
    # PS deliveries to domestic 119.01
# PS total s-s withdrawals total -
    # PS total s-s withdrawals.1 -
    # PS total s-s withdrawals 195.1
        # PS total s-s withdrawals surface -
            # PS s-s surface-water withdrawals.1 -
            # PS s-s surface-water withdrawals 163.52
        # PS total s-s withdrawals groundwater -
            # PS s-s groundwater withdrawals.1 -
            # PS s-s groundwater withdrawals 31.58
# PS total population served 1153.11
    # PS population served by surface 967.160
    # PS population served by groundwater 185.950


# Total Population 1195.16
# year 1985
# county_nm Alameda
# county_cd 1
# state_name California
# state_cd 6

# The csv file with as a data frame
df = pd.read_csv("water_data_clean.csv")
np_data_merge = np.array([[]])
np.set_printoptions(suppress=True)
def main():
    header = df.columns
    # print_col_reversed(header, 0)
    # print(df[header[7:27]])
    # print(df['PS population served by groundwater'].astype(float) + df['PS population served by surface']).astype(float)
    # print(df['PS population served by groundwater'].to_numpy())
    a1 = conv_col_to_float(df['PS population served by groundwater'])
    a2 = conv_col_to_float(df['PS population served by surface'])
    # print(df['PS population served by groundwater'].to_numpy())
    # print(a1)
    print(merge_col(a1, a2, "what"))

# Takes in a column, converts column values to float, zeroes out missing values
# col - the input column 
# returns an np array of the col
def conv_col_to_float(col):
    # print([ord(c) for c in c1[i]])
    return np.array([0.00 if (col[i][0] == str(chr(45))) else float(col[i]) for i in range(len(col))])


# Takes in two columns as np arrays and merges to the new column "name"
# --column data values must be of type float--
# c1 - column 1 as an np array
# c2 - column 2 as an np array
# name - destination column name
# returns a map of name to col
def merge_col(c1, c2, name):
    rel_c1 = c1.copy()
    rel_c2 = c2.copy()
    # print(rel_c1)
    # print(rel_c2)
    # print(name)
    for i in range(len(c1)):
        rel_c1[i] = rel_c1[i] + rel_c2[i]
    return {name:rel_c1}

def print_col_reversed(header, col):
    fCol = df.iloc[col].to_numpy()
    for i in reversed(range(len(header))):
        print(header[i] + " " + str(fCol[i]))

if __name__ == "__main__":
    main()
